name: Build Wipeout Rewrite UWP

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Package Name'
        required: true
        default: 'wipeout-rewrite-uwp'
      tag_name:
        description: 'Tag Name'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: windows-latest  # UWP requires Windows for final packaging
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Initialize project and install dependencies
      - name: Initialize project
        run: |
          npm init -y
          npm install @mattlewis18/capacitor-xbox
          npm install https://github.com/momo-AUX1/UWP.js
          npm install @capacitor/cli @capacitor/core --save-dev

      # Initialize Capacitor after dependencies are installed
      - name: Initialize Capacitor
        run: npx cap init --web-dir www

      # Add UWP platform
      - name: Add UWP platform
        run: npx cap add windows

      # WebAssembly build steps (if needed)
      - name: Set up Emscripten
        if: contains(build.os, 'windows')
        run: |
          choco install cmake python3
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          emsdk install latest
          emsdk activate latest

      - name: Build WebAssembly
        run: |
          cd emsdk
          emsdk_env.bat
          make wasm

      # UWP packaging steps
      - name: Sync Capacitor project
        run: npx cap sync windows

      - name: Build UWP package
        run: |
          cd windows/App
          msbuild /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Never
